---
- name: Check if /etc/network/interfaces exists
  ansible.builtin.stat:
    path: /etc/network/interfaces
  register: interfaces_file

- name: Backup current network interfaces file if it exists
  ansible.builtin.copy:
    src: /etc/network/interfaces
    dest: /etc/network/interfaces.backup
    remote_src: yes
    mode: '0644'
  when: interfaces_file.stat.exists

- name: Ensure /etc/network directory exists
  ansible.builtin.file:
    path: /etc/network
    state: directory
    mode: '0755'

- name: Generate new network interfaces configuration
  ansible.builtin.template:
    src: inter.j2        # located in roles/proxmox/templates/inter.j2
    dest: /etc/network/interfaces
    mode: '0644'
  notify: Restart networking
