
- name: Install Required packages
  hosts: netforge
  become: true
  tasks:
    - name: Install kea-DHCP, BIND, and Step CLI
      dnf:
        name:
          - bind 
          - bind-utils
          - kea-ctrl-agent
          - kea-dhcp4
          - wget 
      state: present


