
- name: Configure StepCA
  hosts: netforge
  become: true
  tasks:
    - name: Deploy StepCA configuration
      copy:
        dest: /etc/step-ca/config/ca.json
        content: |
          {
            "address": "0.0.0.0:443",
            "dnsNames": ["netforge.local"],
            "provisioners": [
              {
                "name": "netforge",
                "type": "JWK",
                "key": "{{ stepca_provisioner_key }}"
              }
            ]
          }

    - name: Start and enable StepCA
      systemd:
        name: step-ca
        state: started
        enabled: true

