---
- name: Complete Proxmox Configuration
  hosts: proxmox
  become: yes
  tasks:
    - name: Disable PVE Enterprise repository
      ansible.builtin.replace:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        regexp: '^deb https://enterprise.proxmox.com/debian/pve'
        replace: '# deb https://enterprise.proxmox.com/debian/pve'
        backup: yes

    - name: Enable PVE No-Subscription repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/pve-no-subscription.list
        line: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
        create: yes
        owner: root
        group: root
        mode: '0644'

    - name: Configure Debian repository sources
      ansible.builtin.blockinfile:
        path: /etc/apt/sources.list
        block: |
          deb http://deb.debian.org/debian bookworm main contrib non-free non-free-firmware
          deb http://deb.debian.org/debian bookworm-updates main contrib non-free non-free-firmware
          deb http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware
        create: yes
        backup: yes

    - name: Add disabled PVE test repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/pve-test.list
        line: "# deb http://download.proxmox.com/debian/pve bookworm pvetest"
        create: yes
        owner: root
        group: root
        mode: '0644'

    - name: Add disabled cep repo
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/ceph.list
        line: "# deb #https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise"
        create: yes
        owner: root
        group: root
        mode: '0644'

    - name: Clean apt cache
      ansible.builtin.apt:
        autoclean: yes

    - name: update apt cache after repository changes
      ansible.builtin.apt:
        update_cache: yes

    - name: Restart pveproxy service
      ansible.builtin.systemd:
        name: pveproxy
        state: restarted

    - name: Upgrade all packages
      ansible.builtin.apt:
       upgrade: dist
       force_apt_get: yes

    - name: Install/Reinstall proxmox-widget-toolkit
      ansible.builtin.apt:
       name: proxmox-widget-toolkit
       state: present
       force: yes
       update_cache: no

    - name: Remove subscription nag from JavaScript file
      ansible.builtin.replace:
       path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
       regexp: "if\\s*\\(res === null.*\\{.*\\}"
       replace: "if (false) {"
       backup: yes

    - name: Disable firmware warning
      ansible.builtin.replace:
       path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
       regexp: "if\\s*\\(res === null.*\\{[\\s\\S]*?\\}\\s*else\\s*if\\s*\\(!premium\\)\\s*\\{.*?\\}"
       replace: "if (false) {"
       backup: yes

    - name: Check if high availability is active
      ansible.builtin.service_facts:
      register: services_state

    - name: Disable high availability services for single node
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - pve-ha-lrm
        - pve-ha-crm
        - corosync
      when: services_state.ansible_facts.services['pve-ha-lrm.service'] is defined and
            services_state.ansible_facts.services['pve-ha-lrm.service'].state == 'running'

    - name: Reboot system if required
      ansible.builtin.reboot:
      when: ansible_facts.uptime_seconds <= 3600
